const SEED_REGALOS = [
  {
    nombre: `Babitas de Tela de Algodón (6+)`,
    categoria: `Alimentación`,
    marcas: `Marcas artesanales de algodón`,
    notas: `El comodín absoluto. Se usan para envolver, limpiar y tapar.`,
    referencia: null,
    estado: `disponible`,
    comprado_por: null,
  },
  {
    nombre: `Bañera Plegable con Soporte`,
    categoria: `Higiene Diaria`,
    marcas: `Stokke (Flexi Bath), Avent, Carestino`,
    notas: `Recomendado por UNICEF para el sueño seguro y comodidad en la lactancia.`,
    referencia: `https://www.mercadolibre.com.ar/p/MLA46191449?matt_tool=89488245&pdp_filters=item_id:MLA1480904375&ua=l7Wl_O3QIEpK_-41glEVcsjgrllqPKI_jCpTwR4TqTcPh30#origin=share&sid=share&wid=MLA1480904375&action=whatsapp`,
    estado: `comprado`,
    comprado_por: `Ya resuelto`,
  },
  {
    nombre: `Bodys x4 (3 de 0 a 3 meses y 2 de +3 meses)`,
    categoria: `Textil`,
    marcas: `Se pueden juntar 2 personas`,
    notas: null,
    referencia: null,
    estado: `comprado`,
    comprado_por: `Ya resuelto`,
  },
  {
    nombre: `Cuna Colecho`,
    categoria: `Sueño Seguro`,
    marcas: `Maxi-Cosi (Iora), Safety 1st, Carestino`,
    notas: `Bañeras elevadas cuidan la espalda de los padres; las plegables ahorran espacio.`,
    referencia: null,
    estado: `comprado`,
    comprado_por: `Ferchu`,
  },
  {
    nombre: `Cambiador portatil plegable`,
    categoria: `Higiene Diaria`,
    marcas: null,
    notas: null,
    referencia: `https://articulo.mercadolibre.com.ar/MLA-1442907459-cambiador-para-bebes-impermeable-elegir-estampa-_JM?searchVariation=184221583557#polycard_client=search-desktop&searchVariation=184221583557&float_highlight=last_unit&be_origin=backend&overlay_label=not_apply&search_layout=grid&position=5&type=item&tracking_id=3fd8e7c3-6338-4d0d-b2ff-b690c41004e5&sid=search`,
    estado: `disponible`,
    comprado_por: null,
  },
  {
    nombre: `Cambiador Fijo antivuelco`,
    categoria: `Higiene Diaria`,
    marcas: null,
    notas: null,
    referencia: `https://articulo.mercadolibre.com.ar/MLA-852427151-cambiador-bebe-fijo-con-bordes-antivuelco-babyfactoryshop-_JM?searchVariation=175913280142#polycard_client=search-desktop&searchVariation=175913280142&be_origin=backend&overlay_label=not_apply&search_layout=grid&position=9&type=item&tracking_id=f0d47c0c-8a12-4141-93f2-d2ba760fd3d2&sid=search`,
    estado: `disponible`,
    comprado_por: null,
  },
  {
    nombre: `Chupetes x 3`,
    categoria: `Control`,
    marcas: null,
    notas: null,
    referencia: null,
    estado: `disponible`,
    comprado_por: null,
  },
  {
    nombre: `Fular o Mochila Ergonómica`,
    categoria: `Paseo`,
    marcas: `Ergobaby, Huggy, Meyco`,
    notas: null,
    referencia: null,
    estado: `disponible`,
    comprado_por: null,
  },
  {
    nombre: `Mamaderas Set Anticolic Philips Avent Scy119/18 Triple Pack`,
    categoria: `Alimentación`,
    marcas: null,
    notas: null,
    referencia: `https://www.mercadolibre.com.ar/mamaderas-set-anticolic-philips-avent-scy11918-triple-pack/up/MLAU358618446?pdp_filters=official_store%3A629%7Cdeal%3AMLA1694874-1#polycard_client=search-desktop&be_origin=backend&overlay_label=not_apply&search_layout=grid&position=3&type=product&tracking_id=7469b2b6-09a8-4d6a-90c3-1e29540b25c6&wid=MLA1741748862&sid=search`,
    estado: `disponible`,
    comprado_por: null,
  },
  {
    nombre: `Mantas Recibidoras (4-6 uds)`,
    categoria: `Textil`,
    marcas: `Mellow, Carter's, Marcas Locales`,
    notas: null,
    referencia: null,
    estado: `comprado`,
    comprado_por: `Ya resuelto`,
  },
  {
    nombre: `Mochila parental`,
    categoria: `Paseo`,
    marcas: null,
    notas: null,
    referencia: `https://articulo.mercadolibre.com.ar/MLA-1460816995-mochila-bolso-maternal-calidad-premium-cuna-cambiador-3-en-1-_JM?searchVariation=186063021873#polycard_client=search-desktop&searchVariation=186063021873&be_origin=backend&overlay_label=not_apply&search_layout=grid&position=12&type=item&tracking_id=496bedc3-5f69-47a6-8532-4c5cfc2bbad0&sid=search`,
    estado: `disponible`,
    comprado_por: null,
  },
  {
    nombre: `Monitor con Videocámara`,
    categoria: `Tecnología`,
    marcas: `Motorola Baby, Philips Avent`,
    notas: `Bañeras elevadas cuidan la espalda de los padres; las plegables ahorran espacio.`,
    referencia: `https://www.mercadolibre.com.ar/2-camaras-de-seguridad-ezviz-ty1-wi-fi-full-hd-interior/up/MLAU3571209478?pdp_filters=item_id%3AMLA2577674516&from=gshop&matt_tool=74855370&matt_word=&matt_source=google&matt_campaign_id=23390548772&matt_ad_group_id=189479893143&matt_match_type=&matt_network=g&matt_device=c&matt_creative=789984781663&matt_keyword=&matt_ad_position=&matt_ad_type=pla&matt_merchant_id=543134391&matt_product_id=MLAU3571209478&matt_product_partition_id=2454529399814&matt_target_id=aud-2430760955230:pla-2454529399814&cq_src=google_ads&cq_cmp=23390548772&cq_net=g&cq_plt=gp&cq_med=pla&gad_source=1&gad_campaignid=23390548772&gbraid=0AAAAAD01zQaonpy77yK-gFFyPgc_swVFD&gclid=CjwKCAjw7KvTBhA6EiwAWnutYdkjcCh33KxVuJh9FR3pGnEterNQXLqM3ysB3zP0r6SUe6_-ur6c0xoCetcQAvD_BwE`,
    estado: `disponible`,
    comprado_por: null,
  },
  {
    nombre: `Tacho pañales antiolor`,
    categoria: `Higiene Diaria`,
    marcas: null,
    notas: null,
    referencia: `https://www.mercadolibre.com.ar/tacho-cesto-para-panales-basura-hermetico-anti-olores-bebe-blanco/p/MLA65630282#polycard_client=search-desktop&be_origin=backend&overlay_label=not_apply&search_layout=grid&position=5&type=product&tracking_id=0638c913-4d0d-4ecc-8575-c409789e28cd&wid=MLA3663834746&sid=search`,
    estado: `disponible`,
    comprado_por: null,
  },
  {
    nombre: `Termómetro Digital de Oído/Frente`,
    categoria: `Botiquín`,
    marcas: `Braun (Thermoscan), Citizen`,
    notas: `Esencial que sean de toalla gruesa y algodón suave.`,
    referencia: null,
    estado: `disponible`,
    comprado_por: null,
  },
  {
    nombre: `Toallas con Capucha (3 uds)`,
    categoria: `Higiene Diaria`,
    marcas: `Baby Cottons, Carter's`,
    notas: `Recomendado por dermatólogos sobre las toallitas húmedas corporales en el primer mes.`,
    referencia: null,
    estado: `disponible`,
    comprado_por: null,
  },
  {
    nombre: `Viandas de Comida Congelada`,
    categoria: `Red de Apoyo`,
    marcas: `Simpleat, Servicios Locales`,
    notas: `Validado por pediatras. Mediciones rápidas sin incomodar al bebé.`,
    referencia: null,
    estado: `comprado`,
    comprado_por: `Mechi`,
  },
  {
    nombre: `Nido de contención`,
    categoria: `Descanso`,
    marcas: null,
    notas: `Tijeras de punta roma o limas eléctricas seguras para recién nacidos.`,
    referencia: `https://articulo.mercadolibre.com.ar/MLA-901379298-nido-de-contencion-con-almohadon-cervical-para-bebe-_JM?searchVariation=203736599699#polycard_client=search-desktop&searchVariation=203736599699&float_highlight=last_units&be_origin=backend&overlay_label=not_apply&search_layout=grid&position=5&type=item&tracking_id=c44f75e4-43f6-4077-b0c4-18bea7a5ea2f&sid=search`,
    estado: `disponible`,
    comprado_por: null,
  },
  {
    nombre: `Gimnasio + alfombra multifuncional`,
    categoria: `Estimulación`,
    marcas: null,
    notas: `Brinda soporte ergonómico para la espalda de la mamá y el bebé.`,
    referencia: `Victoria Dri`,
    estado: `disponible`,
    comprado_por: null,
  },
  {
    nombre: `Esterilizador de mamilas AVENT`,
    categoria: `Higiene Diaria`,
    marcas: null,
    notas: `Para limpiar provechitos. Se lavan constantemente.`,
    referencia: `https://www.mercadolibre.com.ar/esterilizador-mamilas-biberon-vapor-philips-scf28102-avent-microondas/p/MLA32867955#polycard_client=search-desktop&be_origin=backend&overlay_label=not_apply&search_layout=grid&position=6&type=product&tracking_id=595cd7f3-5bdf-4b59-be42-74b2ddf2ad6b&wid=MLA1458256829&sid=search`,
    estado: `disponible`,
    comprado_por: null,
  },
  {
    nombre: `Luz Nocturna 670nm`,
    categoria: `Descanso`,
    marcas: null,
    notas: `Modelos compactos con huevito homologado para el auto.`,
    referencia: `https://www.mercadolibre.com.ar/luz-nocturna-roja-670nm-para-dormir-con-temporizador-zxw07/p/MLA2076530907?pdp_filters=item_id%3AMLA3633881114&from=gshop&matt_tool=67379362&matt_word=&matt_source=google&matt_campaign_id=23390549222&matt_ad_group_id=190656559613&matt_match_type=&matt_network=g&matt_device=c&matt_creative=790066498442&matt_keyword=&matt_ad_position=&matt_ad_type=pla&matt_merchant_id=735111307&matt_product_id=MLA2076530907-product&matt_product_partition_id=2396209526128&matt_target_id=aud-2430760955230:pla-2396209526128&cq_src=google_ads&cq_cmp=23390549222&cq_net=g&cq_plt=gp&cq_med=pla&gad_source=1&gad_campaignid=23390549222&gbraid=0AAAAAD01zQYXytaTXvHF8Ej31UQOKA8eT&gclid=CjwKCAjw7KvTBhA6EiwAWnutYS-aun7GiJi8VpO5sla4PkDVVLqBvN_kHxQlFl3FWDQfhydEMU0mMRoCiAgQAvD_BwE`,
    estado: `disponible`,
    comprado_por: null,
  },
  {
    nombre: `Algodón en Discos y Gasas`,
    categoria: `Higiene Diaria`,
    marcas: `Estrella, Johnson's`,
    notas: null,
    referencia: null,
    estado: `disponible`,
    comprado_por: null,
  },
  {
    nombre: `Kit de Aseo (Alicate punta redonda)`,
    categoria: `Botiquín`,
    marcas: `Chicco, Avent, Safety 1st`,
    notas: null,
    referencia: null,
    estado: `disponible`,
    comprado_por: null,
  },
  {
    nombre: `Asesoría de Lactancia`,
    categoria: `Red de Apoyo`,
    marcas: `ACADP, Liga de la Leche`,
    notas: `Un regalo intangible muy valorado si surgen grietas o dudas en la prendida.`,
    referencia: null,
    estado: `disponible`,
    comprado_por: null,
  },
];
